Summary: mtop for mysql 
Name: perl-mtop
Version: 0.6.4.rc1
Release: 1
Copyright: GPL
Group: Applications/CPAN
Source0: mtop-0.6.4.rc1.tar.gz
Url: http://mtop.sourceforge.net/
BuildRoot: /var/tmp/perl-mtop-buildroot/
#BuildRequires: perl >= 5.00503
#Requires: perl >= 5.00503

%description
mtop (MySQL top) monitors a MySQL database showing the queries which are taking the most amount of time to complete. Features include 'zooming' in on a
process to show the complete query, 'explaining' the query optimizer information for a query and 'killing' queries. In addition, server performance statistics,
configuration information, and tuning tips are provided. 

# Provide perl-specific find-{provides,requires}.
#%define __find_provides /usr/lib/rpm/find-provides.perl
#%define __find_requires /usr/lib/rpm/find-requires.perl

%prep
%setup -q -n mtop-%{version} 

%build
CFLAGS="$RPM_OPT_FLAGS" perl Makefile.PL
make
make test

%clean 
rm -rf $RPM_BUILD_ROOT

%install
rm -rf $RPM_BUILD_ROOT
eval `perl '-V:installarchlib'`
mkdir -p $RPM_BUILD_ROOT/$installarchlib
make PREFIX=$RPM_BUILD_ROOT/usr install

[ -x /usr/lib/rpm/brp-compress ] && /usr/lib/rpm/brp-compress

find $RPM_BUILD_ROOT/usr -type f -print | 
	sed "s@^$RPM_BUILD_ROOT@@g" | 
	grep -v perllocal.pod | 
	grep -v "\.packlist" > mtop-0.6.4.rc1-filelist
if [ "$(cat mtop-0.6.4.rc1-filelist)X" = "X" ] ; then
    echo "ERROR: EMPTY FILE LIST"
    exit -1
fi

%files -f mtop-0.6.4.rc1-filelist
%defattr(-,root,root)

%changelog
* Wed Apr 16 2003 Marc Prewitt <mprewitt@chelsea.net>
- Spec file was autogenerated. 
